services:
  web:
    build:  
      context: a-country-front
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./a-country-front:/docker-project
      - /docker-project/node_modules
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll=1000"]